name = "LidDrivenCavity"
uuid = "4dbdb38b-533a-4a7a-8576-5155cac887fa"
authors = ["William F Godoy <williamfgc@yahoo.com>"]
version = "0.1.0"

[deps]
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
YAML = "0.4.14"
